# Generated by Django 4.2.1 on 2023-06-07 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_alter_comment_item_idx'),
        ('market', '0003_love_alter_item_image'),
    ]

    operations = [
    ]
