# Generated by Django 4.2.1 on 2023-05-24 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_message_sender_alter_readreceipt_reader_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='message',
            name='deleted_at',
        ),
    ]
