# Generated by Django 4.2.1 on 2023-05-30 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_remove_message_status_remove_room_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='room',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
