# Generated by Django 4.1 on 2023-05-03 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('transaction_type', models.CharField(max_length=10)),
                ('transaction_location', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('category', models.CharField(max_length=20)),
                ('condition', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
